from pathlib import Path
import re


SOURCE = Path(__file__).resolve().parent.parent / "ch32fun" / "extralibs" / "font_8x8.h"
DEST = Path(__file__).resolve().parent / "font_8x8_rowmajor.h"


def main() -> None:
    source_text = SOURCE.read_text(encoding="latin-1")
    values = [int(match.group(1), 16) for match in re.finditer(r"^\s*0x([0-9a-fA-F]{2})\s*,", source_text, re.MULTILINE)]

    if len(values) != 256 * 8:
        raise SystemExit(f"expected 2048 font bytes, found {len(values)}")

    rows = []
    for glyph_row in range(8):
        row_values = [values[(code * 8) + glyph_row] for code in range(256)]
        rows.append(row_values)

    lines = [
        "/* Generated by generate_font_rowmajor.py from ../ch32fun/extralibs/font_8x8.h */",
        "#ifndef FONT_8X8_ROWMAJOR_H",
        "#define FONT_8X8_ROWMAJOR_H",
        "",
        "static const unsigned char fontdata_rowmajor[8][256] = {",
    ]

    for glyph_row, row_values in enumerate(rows):
        lines.append(f"    /* glyph row {glyph_row} */")
        lines.append("    {")
        for chunk_start in range(0, 256, 16):
            chunk = row_values[chunk_start:chunk_start + 16]
            hex_bytes = ", ".join(f"0x{value:02x}" for value in chunk)
            lines.append(f"        {hex_bytes},")
        lines.append("    },")
    lines.extend([
        "};",
        "",
        "#endif",
        "",
    ])

    DEST.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
